Poročilo o zaključnem računu Evropskega azilnega podpornega urada (EASO) za proračunsko leto 2019
Uvod
Evropski azilni podporni urad (Urad ali EASO) s sedežem v Valletti je bil ustanovljen z Uredbo (EU) št. 439/2010 Evropskega parlamenta in Sveta. Njegov cilj je izboljšati praktično sodelovanje na področju azila in pomagati državam članicam pri izpolnjevanju njihovih evropskih in mednarodnih obveznosti, da zaščitijo ljudi, ki potrebujejo zaščito. Od leta 2015 Urad zagotavlja podporo Grčiji in Italiji v okviru migrantske krize.
Urad operacije, povezane z begunsko krizo, upravlja decentralizirano, saj ima več regionalnih uradov v Italiji in Grčiji ter od leta 2018 tudi na Cipru. Ta decentraliziranost pomeni dodaten pomemben izziv za izvajanje operacij v skladu z veljavnim pravnim okvirom.
Urad je pri izvajanju svojih operacij razmeroma odvisen od sodelovanja držav članic, npr. kar zadeva število nacionalnih strokovnjakov, ki so na voljo v okviru intervencijske skupine za azil (kot je navedeno v členu 15 uredbe o ustanovitvi Urada). Zaradi omejenega števila takšnih nacionalnih strokovnjakov, ki so na voljo, Urad pri opravljanju nalog operativne podpore na terenu še naprej uporablja pogodbene začasne agencijske delavce.
Urad si že od leta 2018 močno prizadeva za izboljšanje svojih sistemov notranje kontrole in je dosegel znaten napredek pri izboljšanju svojih procesov upravljanja.
V EASO je bila leta 2019 ponovno vzpostavljena interna pravna služba. Zaposlen je bil prvi nadzornik za naknadne kontrole in vzpostavljena nova služba za notranjo in naknadno kontrolo. V Uradu so bili sprejeti tudi ukrepi za dodelitev zadostnih sredstev za zaposlovanje in skrajšanje trajanja postopka zaposlovanja. Poleg tega je Urad sprejel popravljalne ukrepe za preprečevanje zamud pri plačilih. Zaradi njih se je znatno zmanjšala stopnja zamud pri plačilih.
Informacije v podkrepitev izjave o zanesljivosti
Revizijski pristop Sodišča vključuje analitične revizijske postopke, neposredno preizkušanje transakcij in oceno ključnih kontrol nadzornih in kontrolnih sistemov Urada. To dopolnjujejo dokazi, pridobljeni z delom drugih revizorjev ter analizo informacij, ki jih je zagotovilo poslovodstvo Urada.
Izjava o zanesljivosti, ki jo Sodišče predloži Evropskemu parlamentu in Svetu – poročilo neodvisnega revizorja
Mnenje
Sodišče je revidiralo:
(a) zaključni račun Urada, ki ga sestavljajo računovodski izkazi in poročila o izvrševanju proračuna za proračunsko leto, ki se je končalo 31. decembra 2019, ter
(b) zakonitost in pravilnost transakcij, povezanih s tem zaključnim računom,
v skladu s členom 287 Pogodbe o delovanju Evropske unije (PDEU).
Zanesljivost zaključnega računa
Mnenje o zanesljivosti zaključnega računa
Po mnenju Sodišča zaključni račun Urada za leto, ki se je končalo 31. decembra 2019, v vseh pomembnih pogledih pošteno predstavlja njegov finančni položaj na dan 31. decembra 2019 ter njegov poslovni izid, denarne tokove in gibanje kapitala za tedaj končano leto v skladu z njegovo finančno uredbo in računovodskimi pravili, ki jih je sprejel računovodja Komisije. Ta pravila temeljijo na mednarodno sprejetih računovodskih standardih za javni sektor.
Zakonitost in pravilnost transakcij, povezanih z zaključnim računom
Prihodki
Mnenje o zakonitosti in pravilnosti prihodkov, povezanih z zaključnim računom
Sodišče meni, da so prihodki, povezani z zaključnim računom za leto, ki se je končalo 31. decembra 2019, v vseh pomembnih pogledih zakoniti in pravilni.
Plačila
Osnova za mnenje s pridržkom o zakonitosti in pravilnosti plačil, povezanih z zaključnim računom
Sodišče je v svojem revizijskem poročilu o Uradu za proračunsko leto 2018 ugotovilo, da so bili postopki javnega naročanja, ki jih je Urad uporabljal za zagotovitev agencijskih delavcev v Italiji, nepravilni. Plačila v višini 13 605 298 EUR, ki jih je Urad na podlagi te pogodbe, podpisane leta 2018, izvršil leta 2019, so zato nepravilna.
Sodišče ugotavlja, da je EASO v letu 2019 izvedel popravljalne ukrepe za odpravo te nepravilnosti.
Sodišče je tudi v svojih revizijskih poročilih o Uradu za proračunski leti 2016 in 2017 ugotovilo, da so bili postopki javnega naročanja, ki jih je Urad uporabljal za zagotovitev agencijskih delavcev v Grčiji in za najem svojih prostorov na Lezbosu, nepravilni. Plačila, ki jih je Urad leta 2019 izvršil na podlagi pogodb, sklenjenih v okviru teh postopkov javnega naročanja iz leta 2016 oziroma 2017, v višini 188 394 EUR oziroma 74 885 EUR, so zato prav tako nepravilna.
Sodišče ugotavlja, da v zvezi s postopki javnega naročanja za agencijske delavce v Grčiji ni več treba izvršiti nobenih plačil. Poleg tega je EASO sprejel popravljalne ukrepe in marca 2018 sklenil novo okvirno pogodbo za začasne storitve.
Urad mora pri izbiri zunanjih strokovnjakov upoštevati načelo enake obravnave, ki je določeno v členu 237 finančne uredbe. Urad je na podlagi razpisa za prijavo interesa, ki je odprt od leta 2015, pripravil seznam zunanjih strokovnjakov z več področij. Sodišče je revidiralo pet primerov. Ugotovilo je, da je v postopkih, ki so se uporabljali za izbiro zunanjih strokovnjakov in sklepanje pogodb z njimi, sistematično manjkala zanesljiva revizijska sled (kot je določeno v členu 36(3) finančne uredbe). Sodišče zlasti ni našlo dokazov, da so bile strokovnjakom dodeljene naloge na podlagi predhodno določenih izbirnih meril v zvezi z nalogami, s katerimi bi se ocenile njihove prednosti v primerjavi z drugimi potencialnimi kandidati. Plačila v višini 111 304 EUR, ki jih je Urad leta 2019 izplačal tem strokovnjakom, so zato prav tako nepravilna.
Skupni znesek, ki ga je EASO v letu 2019 nepravilno izplačal, je znašal 13 979 880 EUR (od tega 13 868 576 EUR izhaja iz nepravilnih postopkov v obdobju 2016–2018). To predstavlja 14,6 % vseh plačil, ki jih je Urad izvršil leta 2019. Ti nepravilni zneski presegajo prag pomembnosti, določen za to revizijo.
Mnenje s pridržkom o zakonitosti in pravilnosti plačil, povezanih z zaključnim računom
Razen v zvezi z zadevami, opisanimi v odstavku o osnovi za mnenje s pridržkom o zakonitosti in pravilnosti plačil, so plačila, povezana z zaključnim računom za leto, ki se je končalo 31. decembra 2019, po mnenju Sodišča v vseh pomembnih pogledih zakonita in pravilna.
Osnova za mnenja
Sodišče je revizijo izvedlo v skladu z mednarodnimi standardi revidiranja (ISA) in etičnim kodeksom MZRS ter mednarodnimi standardi za vrhovne revizijske institucije INTOSAI (ISSAI). Odgovornost Sodišča na podlagi teh standardov je natančneje opisana v delu tega poročila z naslovom Revizorjeva odgovornost. V skladu z etičnim kodeksom za poklicne računovodje, ki ga je izdal Odbor za mednarodne etične standarde za računovodje (kodeks IESBA), ter etičnimi zahtevami, relevantnimi za revizijo, ki jo izvaja Sodišče, je Sodišče neodvisno, poleg tega pa izpolnjuje tudi druge etične obveznosti v skladu s temi zahtevami in kodeksom IESBA. Sodišče meni, da so pridobljeni revizijski dokazi zadostna in ustrezna podlaga za njegovo mnenje.
Odgovornosti poslovodstva in odgovornih za upravljanje
V skladu s členi 310 do 325 PDEU in finančno uredbo Urada je poslovodstvo Urada odgovorno za pripravo in predstavitev njegovega zaključnega računa na podlagi mednarodno sprejetih računovodskih standardov za javni sektor ter za zakonitost in pravilnost transakcij, povezanih z zaključnim računom. To vključuje zasnovo, izvajanje in vzdrževanje notranjih kontrol, ki se uporabljajo za pripravo in predstavitev računovodskih izkazov brez pomembno napačne navedbe zaradi goljufije ali napake. Poslovodstvo je odgovorno tudi za zagotavljanje skladnosti dejavnosti, finančnih transakcij in informacij v računovodskih izkazih z uradnimi zahtevami, ki veljajo zanje. Končno odgovornost za zakonitost in pravilnost transakcij, povezanih z zaključnim računom Urada, ima poslovodstvo Urada.
Pri pripravi zaključnega računa je poslovodstvo odgovorno za oceno zmožnosti Urada za časovno neomejenost delovanja. Poslovodstvo mora razkriti zadeve, povezane s časovno neomejenostjo delovanja Urada, kadar je to ustrezno, ter uporabljati računovodenje na podlagi predpostavke o časovni neomejenosti delovanja, razen če poslovodstvo namerava likvidirati subjekt ali nehati poslovati ali če nima druge možnosti, kot da to stori.
Naloga odgovornih za upravljanje je nadzor nad procesom računovodskega poročanja Urada.
Revizorjeva odgovornost za revizijo zaključnega računa in z njim povezanih transakcij
Cilj Sodišča je pridobiti sprejemljivo zagotovilo o tem, ali je zaključni račun Urada brez pomembno napačne navedbe in ali so transakcije, povezane z zaključnim računom, zakonite in pravilne, ter na podlagi svoje revizije Evropskemu parlamentu in Svetu ali drugim organom za razrešnico zagotoviti izjavo o zanesljivosti zaključnega računa Urada ter o zakonitosti in pravilnosti z njim povezanih transakcij. Sprejemljivo zagotovilo je visoka raven zagotovila, vendar ni nujno, da se z revizijo vedno odkrije obstoječa pomembno napačna navedba ali neskladnost. Do napačne navedbe ali neskladnosti lahko pride zaradi goljufije ali napake, za pomembne pa štejejo, če se lahko utemeljeno pričakuje, da bodo ločeno ali skupaj vplivale na ekonomske odločitve, ki bi jih uporabniki sprejeli na podlagi tega zaključnega računa.
Sodišče v zvezi s prihodki preverja subvencije, prejete od Komisije ali sodelujočih držav, ter oceni postopke Urada za pobiranje morebitnih pristojbin in drugih prihodkov.
Pri odhodkih Sodišče preuči plačilne transakcije ob nastanku, evidentiranju in sprejetju odhodkov. Ta preučitev zajema vse kategorije plačil (vključno z nakupom sredstev) razen predujmov ob njihovem nastanku. Predplačila so preučena, ko prejemnik sredstev utemelji njihovo pravilno porabo in Urad sprejme utemeljitev z obračunom predplačila v istem letu ali pozneje.
Sodišče v skladu z mednarodnimi standardi revidiranja (ISA) in mednarodnimi standardi za vrhovne revizijske institucije (ISSAI) med celotno revizijo uporablja strokovno presojo in ohranja strokovno skrbnost. Poleg tega:
Ugotavlja in ocenjuje tveganja pomembno napačnih navedb v zaključnem računu in pomembnih neskladij z njim povezanih transakcij z zahtevami pravnega okvira Evropske unije zaradi goljufije ali napake, pripravlja in izvaja revizijske postopke glede na ta tveganja ter pridobiva revizijske dokaze, ki so zadostna in ustrezna podlaga za njegovo mnenje. Tveganje, da se ne odkrijejo pomembno napačne navedbe ali neskladja, ki so posledica goljufij, je večje, kot da se ne odkrijejo pomembno napačne navedbe ali neskladja, ki so posledica napake, saj goljufije lahko vključujejo dogovarjanje, ponarejanje, načrtne opustitve, zavajajoče razlage ali pa izogibanje notranjim kontrolam,
Skuša razumeti notranje kontrole, relevantne za revizijo, da se pripravijo okoliščinam primerni revizijski postopki, vendar ne za izrekanje mnenja o uspešnosti notranjih kontrol,
Vrednoti ustreznost uporabljenih računovodskih usmeritev in utemeljenost računovodskih ocen in z njimi povezanih razkritij poslovodstva,
Sprejema zaključke o ustreznosti tega, da je poslovodstvo uporabilo računovodstvo na osnovi predpostavke o zmožnosti časovne neomejenosti delovanja, ter glede na pridobljene revizijske dokaze tudi o tem, ali obstaja pomembna negotovost v zvezi z dogodki ali razmerami, ki bi lahko pomenili precejšen dvom o zmožnosti Urada za časovno neomejenost delovanja. Če ugotovi, da pomembna negotovost obstaja, mora v svojih revizijskih poročilih opozoriti na s tem povezana razkritja v zaključnem računu ali pa, če so ta razkritja neustrezna, spremeniti svoje mnenje. Zaključki Sodišča temeljijo na revizijskih dokazih, pridobljenih do datuma njegovega revizijskega poročila. Toda zaradi dogodkov ali razmer po tem datumu lahko subjekt preneha nadaljnje delovanje,
Vrednoti celotno predstavitev, strukturo in vsebino zaključnega računa, vključno z razkritji, ter to, ali so v zaključnem računu pošteno predstavljene z njim povezane transakcije in dogodki,
Pridobiva zadostne ustrezne revizijske dokaze o finančnih informacijah Urada, da bi lahko dalo mnenje o zaključnem računu in z njim povezanih transakcijah. Odgovorno je za usmerjanje, nadzor in izvedbo revizije. Revizijska mnenja so izključno odgovornost Sodišča,
Kadar je bilo to ustrezno, je Sodišče upoštevalo revizijsko delo v zvezi z zaključnim računom Urada, ki ga je opravil neodvisni zunanji revizor, kot je določeno v členu 70(6) finančne uredbe EU.
Sodišče komunicira s poslovodstvom, med drugim glede načrtovanega obsega in časovnega razporeda revizij ter pomembnih revizijskih ugotovitev, vključno z morebitnimi pomembnimi pomanjkljivostmi notranjih kontrol, ki jih odkrije pri svoji reviziji. 
Od zadev, o katerih komunicira z Uradom, določi tiste, ki so bile najpomembnejše pri reviziji zaključnega računa za tekoče obdobje in so zato ključne revizijske zadeve. 
Te zadeve opiše v revizijskem poročilu, razen če je z zakoni ali predpisi prepovedano javno razkritje zadeve ali, v izredno redkih okoliščinah, če ugotovi, da se o zadevi v njegovem poročilu ne bi smelo poročati, ker bi bilo smiselno pričakovati, da bodo neugodne posledice tega poročanja večje od koristi javnega interesa.
Spremljanje upoštevanja opažanj iz prejšnjih let
Pregled ukrepov, sprejetih na podlagi opažanj Sodišča iz prejšnjih let, je v Prilogi.
To poročilo je sprejel senat IV, ki ga vodi Alex Brenninkmeijer, član Evropskega računskega sodišča, v Luxembourgu 22. septembra 2020.
Za Evropsko računsko sodišče
Klaus-Heiner Lehne Predsednik
Priloga – Spremljanje upoštevanja opažanj iz prejšnjih let
Veliko plačil je bilo izvršenih po roku, določenem v finančni uredbi.
Kljub večkratnim poskusom EASO ni uspel zaposliti dovolj osebja.
Urad je imel težave z ohranitvijo uslužbencev.
Urad ni imel skupine za notranjo revizijo.
Urad nima notranje pravne službe niti sistematičnega postopka za notranji pregled pravnih dokumentov. Za večino svojega pravnega dela je najemal zunanje izvajalce, vendar ni sprejel jasnih notranjih odločitev ali smernic, ki bi to urejale.
Spremljanje pogodb glede izpolnjevanja nacionalnih pravil o začasnih delavcih je bilo slabo.
Evropsko računsko sodišče je seznanjeno s tem, da na Sodišču Evropske unije poteka postopek v zadevi, v kateri se obravnava več vprašanj v zvezi s tem, kako agencije EU uporabljajo Direktivo 2008/104/ES Evropskega parlamenta in Sveta z dne 19. novembra 2008 o začasnih agencijskih delavcih v agencijah EU.
Ker bo odgovor Sodišča Evropske unije na ta vprašanja lahko imel učinek na stališče Evropskega računskega sodišča v zvezi z uporabo agencijskih delavcev v okviru Urada, se Evropsko računsko sodišče ne bo izreklo glede spremljanja upoštevanja opažanj iz prejšnjih let v zvezi s tem, dokler Sodišče Evropske unije ne bo presodilo o navedeni zadevi.
V preverjanju evidenc opravljenih ur in nepravilnosti so bile pomembne slabosti.
Sodišče je leta 2017 ugotovilo, da so postopki Urada za spremljanje odhodkov v zvezi s potovanji šibki. Pri tem se zlasti pogosto niso zahtevala dokazila. Zadevo Urad notranje preiskuje.
Na naslednjih področjih so obstajale pomembne slabosti: priprava razpisnih zahtev; upoštevani postopki javnega naročanja; roki, določeni za predložitev ponudb; metode za vrednotenje in dodelitev; podaljšanja pogodb; izvajanje pogodb in preverjanje zagotovljenih storitev.
Na naslednjih področjih so obstajale pomembne slabosti: ocena potreb; izbira vrste pogodb; spremembe pogodb.
Pogodbe za opravljanje storitev s podjetji IT so bile ubesedene tako, da bi lahko pomenile napotitev („mise à disposition”) začasnih agencijskih delavcev namesto jasno opredeljenih storitev ali proizvodov IT. To je v nasprotju s kadrovskimi predpisi EU ter socialno- in delovnopravnimi določbami EU. Urad bi moral zagotoviti, da so pogodbe oblikovane tako, da se prepreči kakršna koli zmeda med javnim naročanjem storitev IT in najemanjem agencijskih delavcev.
V postopku za oddajo javnega naročila za sklenitev okvirne pogodbe za zagotovitev agencijskih delavcev v Italiji ni bilo upoštevano načelo poštene konkurence zaradi bistvenih napak v tehničnih specifikacijah in pri zadevnih pogajanjih. Urad bi moral strogo uporabljati pravila EU za javno naročanje.
Akcijski načrt Urada o upravljanju je vključeval oceno izvajanja njegovih standardov notranje kontrole. V oceni so bile odkrite bistvene slabosti in neučinkovitosti pri večini standardov notranje kontrole in meril za ocenjevanje.
Urad bi moral vzpostaviti uspešne naknadne kontrole.
Urad ni imel sistematičnega postopka za interni pregled pravnih dokumentov. Sodišče je odkrilo več nedoslednosti v zvezi s pravnimi vidiki postopkov javnega naročanja. Urad bi moral vzpostaviti notranjo pravno službo skupaj z uspešnim sistemom za upravljanje pravnih postopkov in dokumentov.
Urad bi moral vzpostaviti uspešno politiko o občutljivih delovnih mestih.
Urad bi moral vzpostaviti uspešno politiko za upravljanje najetih prostorov in z njimi povezanih storitev.
Omejeni prvotni letni proračuni in to, da v proračunu Urada ni sredstev za nepredvidljive dogodke, s katerimi bi se krilo financiranje nepredvidenih nujnih operativnih potreb, so povzročali proračunske negotovosti in ovirali načrtovanje za izredne razmere. Urad bi moral take proračunske omejitve še naprej obravnavati v posvetovanju s Komisijo in proračunskimi organi.
Odgovor agencije
Urad EASO je dejansko že potrdil, da sprejema ugotovitve Sodišča v zvezi z letom 2018. Kot je bilo Sodišče obveščeno, je urad EASO ob imenovanju novega izvršnega direktorja urada junija 2019 in po objavi poročila Sodišča oktobra 2019 takoj začel izvajati popravne ukrepe:
prekinil je okvirno pogodbo;
objavil je nov javni razpis za storitve agencijskih delavcev v Italiji;
precej je zmanjšal število agencijskih delavcev, napotenih v Italijo, kljub temu pa je skupaj z italijansko vlado zagotavljal neprekinjeno izvajanje dejavnosti na terenu;
objavil je dodatni razpis za strokovnjake iz držav članic in, kadar je bilo to mogoče, uporabil alternativne načine za napotitev strokovnjakov, in sicer za čas do sklenitve nove okvirne pogodbe, kar je bilo izvedeno decembra 2019.
Urad EASO je moral neprekinjeno poslovanje razumno zagotoviti vsaj za nekatere ključne podporne ukrepe v Italiji. Zato ni mogel nemudoma prekiniti izvajanja tedaj veljavne okvirne pogodbe (in posebnih pogodb), dokler so se izvajali popravni ukrepi.
Urad EASO je dejansko že potrdil, da sprejema ugotovitve Sodišča za prej omenjena leta pred letom 2019. Urad želi poudariti, da je bila okvirna pogodba, sklenjena na podlagi izrednega postopka, za izvajanje začasnih storitev v Grčiji prekinjena leta 2018. Znesek, izplačan v letu 2019 na podlagi te okvirne pogodbe, se nanaša na odškodnine, ki jih je moral urad plačati zaradi prekinitve omenjene pogodbe. Navedena plačila so bila tako posledica popravnih ukrepov, ki jih je urad izvedel, da bi zagotovil pravilnost poslovanja.
Od marca 2018 urad EASO posluje z novo okvirno pogodbo za podobne storitve.
Urad EASO je seznanjen s to ugotovitvijo Sodišča.
Urad EASO upravlja svoje strokovnjake v skladu s pojasnjevalno opombo Evropske komisije o postopku, ki se uporablja za uporabo in izbiro zunanjih strokovnjakov (objavljeno na spletišču Budgweb).
Na podlagi veljavnega pravnega okvira je besedilo razpisa za prijavo interesa podrobneje opisano (za notranje namene) v upravni okrožnici o upravljanju razpisa za prijavo interesa za zunanje strokovnjake (ref. št. EASO/DOA/2018/441).
V zvezi s tem ima obvestilo k dokumentaciji v zvezi z izbiro posebnega(-ih) strokovnjaka(-ov) za nalogo dvojni namen: uporablja se za utemeljitev odločitve o izbiri strokovnjaka z vzpostavljenega seznama, pri čemer so v obvestilu navedeni razlogi, zakaj se je zadevni strokovnjak štel za (najbolj) primernega, in kot sled za revizijo.
Nazadnje, urad EASO je leta 2020 objavil nov razpis za prijavo interesa. V skladu s tem bo uveden nov postopek, pri čemer se bodo upoštevale ugotovitve in se bo izboljšala utemeljitev izbire zadevnega strokovnjaka v primerjavi z drugimi strokovnjaki, vključenimi na seznam.
Urad EASO je seznanjen s to ugotovitvijo Sodišča. Urad EASO želi tudi znova poudariti, da je bila izvedba plačil v zvezi z okvirno pogodbo za agencijske delavce v Italiji nujna zaradi operativnih potreb v skladu z zavezo EU za zagotavljanje nujne pomoči Italiji.
Urad EASO sicer razume razloge za mnenje s pridržki, vendar meni, da bi Sodišče lahko svojo presojo omililo zaradi zadevnih operativnih potreb. Sočasno urad potrjuje zavezanost za nadaljnje izboljševanje svojega poslovanja.
AVTORSKE PRAVICE
Evropska unija, 2020
Politika Evropskega računskega sodišča (Sodišča) glede ponovne uporabe se izvaja s sklepom Decision of the European Court of Auditors No 6-2019 o politiki odprtih podatkov in ponovni uporabi dokumentov.
Če ni drugače navedeno (npr. v posameznih obvestilih o avtorskih pravicah), so vsebine Sodišča, ki so v lasti EU, pod licenco Creative Commons Attribution 4.0 International (CC BY 4.0). To pomeni, da je ponovna uporaba dovoljena, če se ustrezno navede vir in označijo spremembe. Oseba, ki dokumente ponovno uporabi, ne sme potvoriti njihovega prvotnega pomena ali sporočila. Sodišče ni odgovorno za morebitne posledice ponovne uporabe.
Če so na gradivu prikazane določljive fizične osebe, npr. na fotografijah uslužbencev Sodišča, ali če gradivo vsebuje dela tretjih strani, je treba pridobiti dodatne pravice. Kadar je pridobljeno dovoljenje, to razveljavi zgoraj omenjeno splošno dovoljenje, zato morajo biti v njem jasno navedene omejitve glede uporabe.
Za uporabo in prikazovanje vsebin, katerih lastnica ni EU, je morda treba pridobiti dovoljenje neposredno od imetnikov avtorskih pravic.
Programska oprema ali dokumenti, za katere veljajo pravice industrijske lastnine, kot so patenti, blagovne znamke, registrirani modeli, logotipi in imena, niso vključeni v politiko Sodišča glede ponovne uporabe in vam niso dani na voljo v okviru licence.
Na spletiščih institucij Evropske unije znotraj domene europa.eu so povezave do spletišč tretjih oseb. Ker Sodišče na ta spletišča ne more vplivati, vas poziva, da preberete njihove dokumente o politiki glede varstva osebnih podatkov in avtorskih pravic.
Uporaba logotipa Evropskega računskega sodišča
Logotip Sodišča se ne sme uporabiti brez njegove predhodne privolitve.